name: Rust

on:
  push:
    branches: 
      - main
      - release/*
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Jimver/cuda-toolkit@v0.2.11
      id: cuda-toolkit
      with:
        cuda: '12.2.0'
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test --verbose
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build CPU release
      run: |
            RUNNER_ALLOW_RUNASROOT=1 sudo apt-get install pkg-config musl-tools
            rustup target add x86_64-unknown-linux-musl
            cargo build -r --target x86_64-unknown-linux-musl
            
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload CPU Version Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}

        asset_path: ./target/x86_64-unknown-linux-musl/release/aaml
        asset_name: aaml-cpu
        asset_content_type: application/octet-stream

    - name: Build GPU release
      run: |
            RUNNER_ALLOW_RUNASROOT=1 sudo apt-get install pkg-config musl-tools
            rustup target add x86_64-unknown-linux-musl
            cargo build -r --target x86_64-unknown-linux-musl --features cuda

    - name: Upload GPU Version Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}

        asset_path: ./target/x86_64-unknown-linux-musl/release/aaml
        asset_name: aaml-gpu
        asset_content_type: application/octet-stream